openapi: 3.0.4
info: 
  version: '1.0'
  title: "Hobby Lobby API"
  description: API for groups, meetings, places and activities
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/v1
    description: Localhost

paths:   
  /groups/feed:
    get:
      summary: Get public feed of groups
      parameters:
        - in: query
          name: filter
          description: Filters for the feed
          required: false
          schema:
            type: string
            enum: [new, trending, recommended]
            default: new
        - in: query
          name: order
          description: Chronological order
          required: false
          schema: 
            type: string
            enum: [asc, desc]
            default: desc
        - in: query
          name: tags
          description: Filter by specific tags
          schema:
            type: string
      responses:
        '200':
          description: List of groups found
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/GroupResponse"
        '204': 
          description: No groups available for selected filters
    

  /groups:
    get:
      summary: Get list of personal/all groups
      parameters:
        - in: query
          name: userId
          schema: 
            type: string
          description: "User ID to only show personal groups"
      responses:
        '200': 
          description: List of groups obtained
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: "#/components/schemas/GroupResponse"
        '204': 
          description: No groups found
    post:
      summary: Create new group
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/GroupCreateRequest"
      responses:
        '201': 
          description: 'Group created successfully'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GroupResponse"
        '400':
          description: Mandatory fields missing or invalid
        '401':
          description: User not authenticated
  
  /groups/{id}:
    get:
      summary: Get the details of a group
      parameters:
        - in: path
          name: id
          required: true
          schema:	
            type: string
      responses: 
        '200': 
          description: Details of the group obtained
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GroupResponse"
        '404': 
          description: Group not found
    delete:
      summary: Delete a group
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Group deleted
        '403':
          description: Only the owner can delete the group
        '404':
          description: Group not found
    patch:
      summary: Partially change a group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GroupUpdateRequest"
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Group updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GroupResponse"
        '400': 
          description: Invalid data
        '401': 
          description: User not authenticated
        '404':
          description: Group not found
  
  /groups/{id}/join:
    post:
      summary: Join a group
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully joined the group
        '409':
          description: Already a member
          	
  /groups/{group_id}/meetings:
    post:
      summary: Create a new meeting for a group
      parameters:
        - in: path
          name: group_id
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MeetingCreateRequest"
      responses:
        '201':
          description: Meeting created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MeetingResponse"
        '400':
          description: Invalid data
        '401':
          description: User not authenticated
        '404':
          description: Group not found
    get:
      summary: Get list of meetings of a group
      parameters:
        - in: path
          name: group_id
          required: true
          schema: 
            type: string
      responses:
        '200': 
          description: List of meetings of the group obtained
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeetingResponse"
        '404': 
          description: Group not found
  
  /groups/{group_id}/meetings/{meeting_id}:
    get:
      summary: Get details of a meeting
      parameters:
        - in: path
          name: group_id
          required: true
          schema:
            type: string
        - in: path
          name: meeting_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the meeting obtained
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeetingResponse"
        '404':
          description: Group or meeting not found
    patch:
      summary: Partially change a meeting
      parameters:
        - in: path
          name: group_id
          required: true
          schema:
            type: string
        - in: path
          name: meeting_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MeetingUpdateRequest"
      responses:
        '200': 
          description: Meeting updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeetingResponse"
        '400':
          description: Invalid data
        '401': 
          description: User not authenticated
        '403': 
          description: User not authorized
        '404': 
          description: Group or meeting not found
        '409':
          description: Meeting cannot be updated (already confirmed/rejected)
    delete:
      summary: Delete meeting of a group
      parameters:
        - in: path 
          name: group_id
          required: true
          schema:
            type: string
        - in: path
          name: meeting_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Meeting deleted
        '401':
          description: User not Authenticated
        '403':
          description: User not Authorized
        '404':
          description: Group or meeting not found


  /groups/{group_id}/meetings/{meeting_id}/vote:
    post:
      summary: Send a vote for a meeting
      parameters:
        - in: path
          name: group_id
          required: true
          schema:
            type: string
        - in: path 
          name: meeting_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MeetingVoteCreateRequest"
      responses:
        '201': 
          description: Vote created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeetingVoteResponse"
        '400': 
          description: Invalid data
        '401': 
          description: User not authenticated
        '403': 
          description: User not authorized
        '404': 
          description: Group or meeting not found
        '409':
          description: Vote already sent by user or meeting already confirmed/rejected
                
              


components:
  schemas:
    GroupCreateRequest:
      type: object
      required:
        - groupName
        - tags
        - duration
        - frequency
      properties:
        groupName:
          type: string
          description: Name of the group
        description:
          type: string
          nullable: true
          description: Optional description of the group
        tags:
          type: array
          description: list of tags associated with the group
          items:
            type: string
          minItems: 1
        duration: 
          type: string
          description: Duration of the activity proposed by the group
        frequency:
          type: string
          description: Frequency of the activity proposed by the group

    GroupUpdateRequest:
      type: object
      description: Partial changes to the activity
      minProperties: 1
      properties:
        groupName:
          type: string
          nullable: true 
        description: 
          type: string
          nullable: true
        duration:
          type: string
          nullable: true
        frequency:
          type: string
          nullable: true
        isRecruiting:
          type: boolean
          nullable: true
        tags:
          type: array
          items: 
            type: string   #minItems: 1 ??

    GroupResponse:
      type: object
      required:
        - groupId
        - groupName
        - tags
        - creationDate
        - duration
        - frequency
        - members
        - meetings
        - isRecruiting
        - membersCount
        - self
      properties: 
        groupId:
          type: string
          description: Unique ID of the group
        groupName:
          type: string
          description: Name of the group
        tags:
          type: array
          items:
            type: string
        isRecruiting:
          type: boolean
          description: True if group is looking for members
        members:
          type: array
          description: Members of the group
          items: 
            type: object
        meetings:
          type: array
          description: Meetings of the group
          items: 
              $ref: "#/components/schemas/MeetingResponse"
          default: []
        description: 
          type: string
          description: Info about the group
          nullable: true
        creationDate: 
          type: string
          format: date-time
          description: Timestamp of creation
        duration:
          type: string
        frequency:
          type: string
        membersCount:
          type: integer
        self:
          type: string
          description: Link to group

    MeetingCreateRequest:
      type: object
      required:
        - date
        - time
        - place 
      properties:
        date:
          type: string
          format: date
        time:
          type: string
          format: time
        place:
          type: string
        description:
          type: string
          nullable: true
        minParticipants:
          type: integer
          minimum: 1
          nullable: true
          description: Minimum participants required

    MeetingResponse:
      type: object
      required:
        - meetingId
        - groupId
        - createdBy
        - date
        - time
        - place
        - status
        - totalMembers
        - currentVotes
        - memberVotes
        - self
      properties:
        meetingId:
          type: string
        groupId:
          type: string
        date:
          type: string
          format: date
        time:
          type: string
          format: time
        place:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, confirmed, rejected, needsRevision]
        createdBy: 
          type: string
        totalMembers: 
          type: integer
          minimum: 1
        currentVotes: 
          type: object
          properties:
            confirmed:
              type: integer
              minimum: 0
            rejected:
              type: integer
              minimum: 0
            proposedChange: 
              type: integer
              minimum: 0
        memberVotes:
          type: array
          items:
            $ref: "#/components/schemas/MeetingVoteResponse"
        self:
          type: string
          description: Link to meeting

    MeetingUpdateRequest:
      type: object
      description: Partial changes to the meeting
      minProperties: 1
      properties:
        date:
          type: string
          format: date
          nullable: true
        time: 
          type: string
          format: time
          nullable: true
        place: 
          type: string
          nullable: true

    MeetingVoteResponse:
      type: object
      description: Answer of a member to a meeting
      required:
        - userId
        - response
        - respondedAt
      properties: 
        userId:
          type: string
        response:
          type: string
          enum: [confirmed, rejected, proposedChange]
        changeProposal:
          type: object
          nullable: true
          properties:
            date:
              type: string
              format: date
              nullable: true
            time:
              type: string
              format: time
              nullable: true
            place:
              type: string
              nullable: true
        respondedAt: 
          type: string
          format: date-time

    MeetingVoteCreateRequest: 
      type: object
      required:
        - response
      properties:
        response:
          type: string
          enum: [confirmed, rejected, proposedChange]
        changeProposal:
          type: object
          nullable: true
          properties:
            date:
              type: string
              format: date
              nullable: true
            time: 
              type: string
              format: time
              nullable: true
            place:
              type: string
              nullable: true
    
    


        
